export const USERS_LOAD_START = "USERS_LOAD_START";
export const USERS_LOAD_ERROR = "USERS_LOAD_ERROR";
export const USERS_LOAD_FINISH = "USERS_LOAD_FINISH";
export const USERS_SET = "USERS_SET";
export const USERS_ASYNC_SET = "USERS_ASYNC_SET";
export const USERS_ASYNC_FETCH = "USERS_ASYNC_FETCH";

export const USERGROUPS_LOAD_START = "USERGROUPS_LOAD_START";
export const USERGROUPS_LOAD_ERROR = "USERGROUPS_LOAD_ERROR";
export const USERGROUPS_LOAD_FINISH = "USERGROUPS_LOAD_FINISH";
export const USERGROUPS_SET = "USERGROUPS_SET";
export const USERGROUPS_ASYNC_FETCH = "USERGROUPS_ASYNC_FETCH";
